"""E2E test: Thin definitions.py works in deployed Dagster (AC-1, AC-6).

Verifies that the thin loader shim (generated by generate_entry_point_code())
is correctly discovered by Dagster as a code location, and that expected
assets and resources are available.

This test validates:
- AC-1: Dagster discovers the code location with load_product_definitions
- AC-6: The thin ~17-line definitions.py works in production Dagster

Prerequisites:
    - Kind cluster running with all services: make kind-up
    - Port-forwards active: make test-e2e (manages lifecycle)
    - Demo products deployed: make deploy-demos

See Also:
    - plugins/floe-orchestrator-dagster/src/floe_orchestrator_dagster/loader.py
    - demo/customer-360/definitions.py (thin shim)
"""

from __future__ import annotations

from pathlib import Path

import httpx
import pytest

DAGSTER_HOST = "127.0.0.1"
DAGSTER_PORT = 3000


@pytest.fixture
def dagster_url() -> str:
    """Get the Dagster webserver URL.

    Returns:
        URL string for Dagster GraphQL endpoint.

    Raises:
        pytest.fail: If Dagster webserver is unreachable.
    """
    url = f"http://{DAGSTER_HOST}:{DAGSTER_PORT}"
    try:
        resp = httpx.get(f"{url}/server_info", timeout=5.0)
        resp.raise_for_status()
    except (httpx.ConnectError, httpx.TimeoutException) as exc:
        pytest.fail(
            f"Dagster webserver not reachable at {url}: {exc}\n"
            "Start infrastructure: make test-e2e"
        )
    return url


@pytest.mark.requirement("AC-1")
@pytest.mark.requirement("AC-6")
def test_dagster_discovers_code_location(dagster_url: str) -> None:
    """Dagster discovers at least one code location from thin definitions.py.

    Queries the Dagster GraphQL API for workspace entries and verifies
    at least one location is loaded and in LOADED status.
    """
    query = """
    {
        workspaceOrError {
            ... on Workspace {
                locationEntries {
                    name
                    loadStatus
                }
            }
        }
    }
    """
    resp = httpx.post(
        f"{dagster_url}/graphql",
        json={"query": query},
        timeout=10.0,
    )
    resp.raise_for_status()
    data = resp.json()

    workspace = data.get("data", {}).get("workspaceOrError", {})
    entries = workspace.get("locationEntries", [])
    assert len(entries) >= 1, (
        f"Expected at least 1 code location, got {len(entries)}. "
        "Is the demo product deployed?"
    )

    loaded = [e for e in entries if e.get("loadStatus") == "LOADED"]
    assert len(loaded) >= 1, (
        f"No code locations in LOADED status. "
        f"Entries: {entries}"
    )


@pytest.mark.requirement("AC-1")
@pytest.mark.requirement("AC-6")
def test_dagster_discovers_assets(dagster_url: str) -> None:
    """Dagster discovers at least one asset from the thin definitions.py.

    Queries the Dagster GraphQL API for asset nodes and verifies at
    least one asset exists, confirming the @dbt_assets from the loader
    are properly registered.
    """
    query = """
    {
        assetNodes {
            assetKey {
                path
            }
        }
    }
    """
    resp = httpx.post(
        f"{dagster_url}/graphql",
        json={"query": query},
        timeout=10.0,
    )
    resp.raise_for_status()
    data = resp.json()

    asset_nodes = data.get("data", {}).get("assetNodes", [])
    assert len(asset_nodes) >= 1, (
        "Expected at least 1 asset from the thin definitions.py loader, "
        f"got {len(asset_nodes)}"
    )


@pytest.mark.requirement("AC-6")
def test_thin_definitions_are_deployed() -> None:
    """Verify the deployed definitions.py files are thin loader shims.

    Reads the demo definitions.py files and confirms they use
    load_product_definitions (not the old 187-line template).
    """
    demo_dir = Path(__file__).resolve().parents[2] / "demo"
    products = ["customer-360", "financial-risk", "iot-telemetry"]

    for product in products:
        defs_path = demo_dir / product / "definitions.py"
        if not defs_path.exists():
            pytest.fail(f"definitions.py not found at {defs_path}")

        content = defs_path.read_text()
        assert "load_product_definitions" in content, (
            f"{product}/definitions.py does not use load_product_definitions. "
            "Still using the old 187-line template?"
        )
        lines = content.strip().splitlines()
        assert len(lines) <= 20, (
            f"{product}/definitions.py has {len(lines)} lines, expected <= 20"
        )

        # Verify old patterns are absent
        forbidden = ["_export_dbt_to_iceberg", "_load_iceberg_resources", "get_registry"]
        for pattern in forbidden:
            assert pattern not in content, (
                f"{product}/definitions.py still contains '{pattern}'. "
                "Not using the thin loader pattern."
            )
