{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "floe-platform.prometheus.fullname" . }}
  labels:
    {{- include "floe-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
{{ toYaml .Values.prometheus.config.global | indent 6 }}
    scrape_configs:
      - job_name: floe-otel-collector
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ include "floe-platform.otel.fullname" . }}:{{ .Values.otel.ports.prometheus.servicePort | default 9464 }}
{{- end }}
