{{- if .Values.prometheus.enabled }}
{{- $prometheusName := default (printf "%s-prometheus" (include "floe-platform.fullname" .)) .Values.prometheus.fullnameOverride }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $prometheusName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "floe-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port | default 9090 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "floe-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
