"""Dagster definitions for customer-360 data product.

AUTO-GENERATED by `floe compile` - DO NOT EDIT MANUALLY.

This module provides the Dagster Definitions entry point for the customer-360
data product. It loads the dbt project using dagster-dbt integration.

Regenerate with:
    floe platform compile --spec floe.yaml --manifest manifest.yaml --generate-definitions
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4

from dagster import Definitions
from dagster_dbt import DbtCliResource, DbtProject, dbt_assets
from floe_core.lineage.facets import TraceCorrelationFacetBuilder
from floe_core.plugin_registry import get_registry
from floe_core.plugin_types import PluginType
from floe_core.schemas.compiled_artifacts import CompiledArtifacts
from floe_orchestrator_dagster.lineage_extraction import extract_dbt_model_lineage
from floe_orchestrator_dagster.resources.iceberg import try_create_iceberg_resources
from floe_orchestrator_dagster.resources.lineage import try_create_lineage_resource

# Get the path to this data product's dbt project
PROJECT_DIR = Path(__file__).parent
DBT_PROJECT_DIR = PROJECT_DIR
MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"


ARTIFACTS_PATH = PROJECT_DIR / "compiled_artifacts.json"
DUCKDB_PATH = "/tmp/customer_360.duckdb"


_SAFE_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")


def _is_safe_identifier(name: str) -> bool:
    """Validate a SQL identifier against a safe pattern."""
    return bool(_SAFE_IDENTIFIER_RE.match(name))


def _load_iceberg_resources() -> dict[str, Any]:
    """Load Iceberg resources from compiled_artifacts.json."""
    if not ARTIFACTS_PATH.exists():
        return {}
    artifacts = CompiledArtifacts.model_validate_json(ARTIFACTS_PATH.read_text())
    return try_create_iceberg_resources(
        artifacts.plugins,
        governance=artifacts.governance,
    )


def _export_dbt_to_iceberg(context: Any) -> None:
    """Export dbt model outputs from DuckDB to Iceberg tables."""
    import duckdb
    from pyiceberg.exceptions import NoSuchTableError

    if not Path(DUCKDB_PATH).exists():
        context.log.warning(
            "DuckDB file not found at %s — skipping Iceberg export",
            DUCKDB_PATH,
        )
        return

    if not ARTIFACTS_PATH.exists():
        context.log.warning("compiled_artifacts.json not found — skipping Iceberg export")
        return

    artifacts = CompiledArtifacts.model_validate_json(ARTIFACTS_PATH.read_text())
    if artifacts.plugins is None or artifacts.plugins.catalog is None:
        context.log.info("No catalog plugin configured — skipping Iceberg export")
        return

    catalog_config = artifacts.plugins.catalog.config or {}
    storage_config = artifacts.plugins.storage.config or {} if artifacts.plugins.storage else {}

    registry = get_registry()
    catalog_type = artifacts.plugins.catalog.type
    catalog_plugin = registry.get(PluginType.CATALOG, catalog_type)
    validated_config = registry.configure(PluginType.CATALOG, catalog_type, catalog_config)
    if validated_config is None:
        context.log.warning(
            "Catalog plugin config for %s could not be validated — skipping Iceberg export",
            catalog_type,
        )
        return
    catalog_plugin = type(catalog_plugin)(config=validated_config)
    s3_config = {f"s3.{k}": v for k, v in storage_config.items()}
    catalog = catalog_plugin.connect(config=s3_config)

    product_namespace = "customer_360"

    try:
        catalog.create_namespace(product_namespace)
        context.log.info("Created Iceberg namespace: %s", product_namespace)
    except Exception as exc:
        context.log.debug(
            "Namespace %s exists or creation failed: %s",
            product_namespace,
            type(exc).__name__,
        )

    conn = duckdb.connect(DUCKDB_PATH, read_only=True)
    try:
        tables_df = conn.execute(
            "SELECT table_schema, table_name FROM information_schema.tables "
            "WHERE table_schema NOT IN ('information_schema', 'pg_catalog')"
        ).fetchall()

        for schema_name, table_name in tables_df:
            if not _is_safe_identifier(schema_name) or not _is_safe_identifier(table_name):
                context.log.warning(
                    "Skipping unsafe identifier: %s.%s",
                    schema_name,
                    table_name,
                )
                continue
            if schema_name != "main":
                qualified = f'"{schema_name}"."{table_name}"'
            else:
                qualified = f'"{table_name}"'
            query = f"SELECT * FROM {qualified}"  # nosec B608
            arrow_table = conn.execute(query).fetch_arrow_table()
            if arrow_table.num_rows == 0:
                continue

            iceberg_id = f"{product_namespace}.{table_name}"
            try:
                iceberg_table = catalog.load_table(iceberg_id)
                iceberg_table.overwrite(arrow_table)
            except NoSuchTableError:
                iceberg_table = catalog.create_table(
                    iceberg_id,
                    schema=arrow_table.schema,
                )
                iceberg_table.append(arrow_table)
            context.log.info(
                "Exported %s to Iceberg (%d rows)",
                table_name,
                arrow_table.num_rows,
            )
    finally:
        conn.close()


@dbt_assets(
    manifest=MANIFEST_PATH,
    project=DbtProject(project_dir=DBT_PROJECT_DIR, profiles_dir=DBT_PROJECT_DIR),
    name="customer_360_dbt_assets",
)
def customer_360_dbt_assets(context, dbt: DbtCliResource):
    """Execute customer-360 dbt models as Dagster assets.

    This function is auto-generated by floe compile and uses dagster-dbt
    to execute all dbt models in this project as Dagster software-defined assets.
    """
    _logger = logging.getLogger(__name__)
    lineage = context.resources.lineage
    run_id = None

    # 1. Emit START with trace correlation
    run_facets: dict[str, object] = {}
    try:
        trace_facet = TraceCorrelationFacetBuilder.from_otel_context()
        if trace_facet is not None:
            run_facets["traceCorrelation"] = trace_facet
    except Exception:
        _logger.warning("lineage_trace_facet_failed", exc_info=True)
    try:
        run_id = lineage.emit_start("customer_360_dbt_assets", run_facets=run_facets or None)
    except Exception:
        _logger.warning("lineage_emit_start_failed", exc_info=True)
        run_id = uuid4()

    # 2. Run dbt — on throw: emit FAIL, re-raise
    try:
        yield from dbt.cli(["build"], context=context).stream()
    except Exception as exc:
        try:
            lineage.emit_fail(
                run_id,
                "customer_360_dbt_assets",
                error_message=type(exc).__name__,
            )
        except Exception:
            _logger.warning("lineage_emit_fail_failed", exc_info=True)
        raise

    # 3. Extract per-model lineage with parentRun facets
    try:
        dagster_parent_id = UUID(context.run.run_id)
        events = extract_dbt_model_lineage(
            DBT_PROJECT_DIR,
            dagster_parent_id,
            "customer_360_dbt_assets",
            lineage.namespace,
        )
        for event in events:
            lineage.emit_event(event)
    except Exception:
        _logger.warning("lineage_extraction_failed", exc_info=True)

    # Post-build: export dbt output to Iceberg tables
    _export_dbt_to_iceberg(context)

    # 4. Emit COMPLETE
    try:
        lineage.emit_complete(run_id, "customer_360_dbt_assets")
    except Exception:
        _logger.warning("lineage_emit_complete_failed", exc_info=True)


# Create Definitions object for Dagster to discover
defs = Definitions(
    assets=[customer_360_dbt_assets],
    resources={
        "dbt": DbtCliResource(
            project_dir=DBT_PROJECT_DIR,
            profiles_dir=DBT_PROJECT_DIR,
        ),
        **try_create_lineage_resource(None),
        **_load_iceberg_resources(),
    },
)
