"""Dagster definitions for customer-360 data product.

AUTO-GENERATED by `floe compile` - DO NOT EDIT MANUALLY.

Regenerate with:
    floe platform compile --spec floe.yaml --manifest manifest.yaml --generate-definitions
"""

from __future__ import annotations

from pathlib import Path

from floe_orchestrator_dagster.loader import load_product_definitions

PROJECT_DIR = Path(__file__).parent

defs = load_product_definitions("customer-360", PROJECT_DIR)
