"""Composition error code constants.

This module intentionally has no dependencies so composition internals can use
shared public error codes without importing the compilation error model.
"""

COMPOSITION_PLUGIN_MISSING = "COMPOSITION_PLUGIN_MISSING"
COMPOSITION_PLUGIN_INTERFACE_INVALID = "COMPOSITION_PLUGIN_INTERFACE_INVALID"
COMPOSITION_PLUGIN_CONFIG_INVALID = "COMPOSITION_PLUGIN_CONFIG_INVALID"
COMPOSITION_STORAGE_MISSING = "COMPOSITION_STORAGE_MISSING"
COMPOSITION_PROTOCOL_UNSUPPORTED = "COMPOSITION_PROTOCOL_UNSUPPORTED"
COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED = "COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED"
COMPOSITION_SECRET_PROJECTION_UNSUPPORTED = (
    "COMPOSITION_SECRET_PROJECTION_UNSUPPORTED"  # pragma: allowlist secret
)
COMPOSITION_SECRET_PROVIDER_MISSING = (
    "COMPOSITION_SECRET_PROVIDER_MISSING"  # pragma: allowlist secret
)
COMPOSITION_SECRET_PROVIDER_UNSUPPORTED = (
    "COMPOSITION_SECRET_PROVIDER_UNSUPPORTED"  # pragma: allowlist secret
)
COMPOSITION_IDENTITY_PROVIDER_MISSING = "COMPOSITION_IDENTITY_PROVIDER_MISSING"
COMPOSITION_IDENTITY_PROVIDER_UNSUPPORTED = "COMPOSITION_IDENTITY_PROVIDER_UNSUPPORTED"
COMPOSITION_IDENTITY_MODE_UNSUPPORTED = "COMPOSITION_IDENTITY_MODE_UNSUPPORTED"
COMPOSITION_DEPLOYMENT_BINDING_MISSING = "COMPOSITION_DEPLOYMENT_BINDING_MISSING"
COMPOSITION_RENDERER_PRECONDITION_FAILED = "COMPOSITION_RENDERER_PRECONDITION_FAILED"
COMPOSITION_SEMANTIC_STORAGE_MISSING = "COMPOSITION_SEMANTIC_STORAGE_MISSING"
COMPOSITION_SEMANTIC_CATALOG_MISSING = "COMPOSITION_SEMANTIC_CATALOG_MISSING"
COMPOSITION_SEMANTIC_PROTOCOL_UNSUPPORTED = "COMPOSITION_SEMANTIC_PROTOCOL_UNSUPPORTED"
COMPOSITION_SEMANTIC_CATALOG_UNSUPPORTED = "COMPOSITION_SEMANTIC_CATALOG_UNSUPPORTED"
COMPOSITION_SEMANTIC_TABLE_FORMAT_UNSUPPORTED = "COMPOSITION_SEMANTIC_TABLE_FORMAT_UNSUPPORTED"


__all__ = [
    "COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED",
    "COMPOSITION_DEPLOYMENT_BINDING_MISSING",
    "COMPOSITION_IDENTITY_MODE_UNSUPPORTED",
    "COMPOSITION_IDENTITY_PROVIDER_MISSING",
    "COMPOSITION_IDENTITY_PROVIDER_UNSUPPORTED",
    "COMPOSITION_PLUGIN_CONFIG_INVALID",
    "COMPOSITION_PLUGIN_INTERFACE_INVALID",
    "COMPOSITION_PLUGIN_MISSING",
    "COMPOSITION_PROTOCOL_UNSUPPORTED",
    "COMPOSITION_RENDERER_PRECONDITION_FAILED",
    "COMPOSITION_SECRET_PROJECTION_UNSUPPORTED",
    "COMPOSITION_SECRET_PROVIDER_MISSING",
    "COMPOSITION_SECRET_PROVIDER_UNSUPPORTED",
    "COMPOSITION_SEMANTIC_CATALOG_MISSING",
    "COMPOSITION_SEMANTIC_CATALOG_UNSUPPORTED",
    "COMPOSITION_SEMANTIC_PROTOCOL_UNSUPPORTED",
    "COMPOSITION_SEMANTIC_STORAGE_MISSING",
    "COMPOSITION_SEMANTIC_TABLE_FORMAT_UNSUPPORTED",
    "COMPOSITION_STORAGE_MISSING",
]
