"""Composition error code constants.

This module intentionally has no dependencies so composition internals can use
shared public error codes without importing the compilation error model.
"""

COMPOSITION_PLUGIN_MISSING = "COMPOSITION_PLUGIN_MISSING"
COMPOSITION_PLUGIN_INTERFACE_INVALID = "COMPOSITION_PLUGIN_INTERFACE_INVALID"
COMPOSITION_PLUGIN_CONFIG_INVALID = "COMPOSITION_PLUGIN_CONFIG_INVALID"
COMPOSITION_STORAGE_MISSING = "COMPOSITION_STORAGE_MISSING"
COMPOSITION_PROTOCOL_UNSUPPORTED = "COMPOSITION_PROTOCOL_UNSUPPORTED"
COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED = "COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED"
COMPOSITION_DEPLOYMENT_BINDING_MISSING = "COMPOSITION_DEPLOYMENT_BINDING_MISSING"
COMPOSITION_RENDERER_PRECONDITION_FAILED = "COMPOSITION_RENDERER_PRECONDITION_FAILED"


__all__ = [
    "COMPOSITION_CREDENTIAL_MODE_UNSUPPORTED",
    "COMPOSITION_DEPLOYMENT_BINDING_MISSING",
    "COMPOSITION_PLUGIN_CONFIG_INVALID",
    "COMPOSITION_PLUGIN_INTERFACE_INVALID",
    "COMPOSITION_PLUGIN_MISSING",
    "COMPOSITION_PROTOCOL_UNSUPPORTED",
    "COMPOSITION_RENDERER_PRECONDITION_FAILED",
    "COMPOSITION_STORAGE_MISSING",
]
