"""SLA status tracking and compliance reporting models.

This module defines models for tracking SLA compliance and generating reports:
- SLAStatus: Rolling compliance tracking for a contract/check-type pair
- TrendDirection: Whether metrics are improving, degrading, or stable
- CheckTypeSummary: Summary statistics for a single check type
- SLAComplianceReport: Full compliance report for a contract over a time window

Tasks: T009 (Epic 3D)
Requirements: FR-037, FR-038, FR-039
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from floe_core.contracts.monitoring.violations import ViolationType


class SLAStatus(BaseModel):
    """Rolling SLA compliance tracking for a contract/check-type pair.

    Tracks real-time compliance state over a rolling 24-hour window.
    Updated after each check execution. Used for violation detection
    and severity assignment.

    Attributes:
        contract_name: Name of the contract being tracked.
        check_type: Type of check being tracked.
        current_value: Current metric value (e.g., data age in seconds).
        threshold: SLA threshold value from contract definition.
        compliance_pct: Rolling 24h compliance percentage (0-100).
        last_check_time: When the last check was executed.
        consecutive_failures: Count of consecutive failed checks.
        violation_count_24h: Number of violations in the last 24 hours.
        window_start: Start of the rolling 24h window.

    Example:
        >>> status = SLAStatus(
        ...     contract_name="orders_v1",
        ...     check_type=ViolationType.FRESHNESS,
        ...     current_value=3600.0,
        ...     threshold=7200.0,
        ...     compliance_pct=99.5,
        ...     window_start=datetime.now(tz=timezone.utc),
        ... )
    """

    model_config = ConfigDict(extra="forbid")

    contract_name: str
    check_type: ViolationType
    current_value: float
    threshold: float
    compliance_pct: float = Field(ge=0.0, le=100.0)
    last_check_time: datetime | None = None
    consecutive_failures: int = Field(default=0, ge=0)
    violation_count_24h: int = Field(default=0, ge=0)
    window_start: datetime


class TrendDirection(str, Enum):
    """Direction of a metric trend over time.

    Used in compliance reports to indicate whether metrics are
    improving, degrading, or remaining stable (FR-038).
    """

    IMPROVING = "improving"
    DEGRADING = "degrading"
    STABLE = "stable"


class CheckTypeSummary(BaseModel):
    """Summary statistics for a single check type within a report period.

    Attributes:
        check_type: Type of check summarized.
        total_checks: Total number of checks executed.
        passed_checks: Number of checks that passed.
        failed_checks: Number of checks that failed (violations).
        error_checks: Number of checks that errored.
        compliance_pct: Compliance percentage for the period.
        avg_duration_seconds: Average check execution time.
        violation_count: Total violations detected.
        trend: Whether compliance is improving, degrading, or stable.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    check_type: ViolationType
    total_checks: int = Field(ge=0)
    passed_checks: int = Field(ge=0)
    failed_checks: int = Field(ge=0)
    error_checks: int = Field(ge=0)
    compliance_pct: float = Field(ge=0.0, le=100.0)
    avg_duration_seconds: float = Field(ge=0.0)
    violation_count: int = Field(ge=0)
    trend: TrendDirection = TrendDirection.STABLE


class SLAComplianceReport(BaseModel):
    """Full SLA compliance report for a contract over a time window (FR-037, FR-039).

    Generated by the SLA compliance calculation engine for reporting
    via the library API or `floe sla report` CLI command.

    Attributes:
        contract_name: Name of the contract reported on.
        period_start: Start of the reporting period.
        period_end: End of the reporting period.
        overall_compliance_pct: Overall compliance across all check types.
        check_summaries: Per-check-type summary statistics.
        total_violations: Total violations across all check types.
        total_checks_executed: Total checks executed in the period.
        monitoring_coverage_pct: Percentage of expected checks that executed.
        generated_at: When the report was generated.

    Example:
        >>> report = SLAComplianceReport(
        ...     contract_name="orders_v1",
        ...     period_start=datetime(2026, 1, 1, tzinfo=timezone.utc),
        ...     period_end=datetime(2026, 1, 31, tzinfo=timezone.utc),
        ...     overall_compliance_pct=99.5,
        ...     check_summaries=[],
        ...     total_violations=3,
        ...     total_checks_executed=2880,
        ...     monitoring_coverage_pct=100.0,
        ...     generated_at=datetime.now(tz=timezone.utc),
        ... )
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    contract_name: str
    period_start: datetime
    period_end: datetime
    overall_compliance_pct: float = Field(ge=0.0, le=100.0)
    check_summaries: list[CheckTypeSummary]
    total_violations: int = Field(ge=0)
    total_checks_executed: int = Field(ge=0)
    monitoring_coverage_pct: float = Field(ge=0.0, le=100.0)
    generated_at: datetime
