"""Dagster definitions for financial-risk data product.

AUTO-GENERATED by `floe compile` - DO NOT EDIT MANUALLY.

This module provides the Dagster Definitions entry point for the financial-risk
data product. It loads the dbt project using dagster-dbt integration.

Regenerate with:
    floe platform compile --spec floe.yaml --manifest manifest.yaml --generate-definitions
"""

from __future__ import annotations

from pathlib import Path

from dagster import Definitions
from dagster_dbt import DbtCliResource, dbt_assets

# Get the path to this data product's dbt project
PROJECT_DIR = Path(__file__).parent
DBT_PROJECT_DIR = PROJECT_DIR
MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"


@dbt_assets(
    manifest=MANIFEST_PATH,
    project=DbtCliResource(project_dir=DBT_PROJECT_DIR),
    name="financial_risk_dbt_assets",
)
def financial_risk_dbt_assets(context, dbt: DbtCliResource):
    """Execute financial-risk dbt models as Dagster assets.

    This function is auto-generated by floe compile and uses dagster-dbt
    to execute all dbt models in this project as Dagster software-defined assets.
    """
    yield from dbt.cli(["build"], context=context).stream()


# Create Definitions object for Dagster to discover
defs = Definitions(
    assets=[financial_risk_dbt_assets],
    resources={
        "dbt": DbtCliResource(
            project_dir=DBT_PROJECT_DIR,
            profiles_dir=DBT_PROJECT_DIR,
        ),
    },
)
