"""Dagster definitions for financial-risk data product.

AUTO-GENERATED by `floe compile` - DO NOT EDIT MANUALLY.

This module provides the Dagster Definitions entry point for the financial-risk
data product. It loads the dbt project using dagster-dbt integration.

Regenerate with:
    floe platform compile --spec floe.yaml --manifest manifest.yaml --generate-definitions
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from dagster import Definitions
from dagster_dbt import DbtCliResource, DbtProject, dbt_assets
from floe_core.plugin_registry import get_registry
from floe_core.plugin_types import PluginType
from floe_core.schemas.compiled_artifacts import CompiledArtifacts
from floe_orchestrator_dagster.resources.iceberg import try_create_iceberg_resources
from floe_orchestrator_dagster.resources.lineage import NoOpLineageResource

# Get the path to this data product's dbt project
PROJECT_DIR = Path(__file__).parent
DBT_PROJECT_DIR = PROJECT_DIR
MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"


_LINEAGE_RESOURCE: Any = None


def _load_lineage_resource() -> Any:
    """Load lineage resource from compiled_artifacts.json (lazy).

    Returns a real LineageResource when observability.lineage is enabled
    and a Marquez endpoint is configured. Falls back to NoOpLineageResource
    on any error or missing configuration.
    """
    if not ARTIFACTS_PATH.exists():
        return NoOpLineageResource()
    try:
        artifacts = CompiledArtifacts.model_validate_json(ARTIFACTS_PATH.read_text())
        obs = artifacts.observability
        if obs is None or not obs.lineage:
            return NoOpLineageResource()
        endpoint = getattr(obs, "lineage_endpoint", None)
        transport = getattr(obs, "lineage_transport", "http")
        if not endpoint:
            return NoOpLineageResource()
        namespace = getattr(obs, "lineage_namespace", "default") or "default"
        from floe_core.lineage.emitter import create_emitter
        from floe_orchestrator_dagster.resources.lineage import LineageResource
        transport_config = {"type": transport, "url": endpoint}
        emitter = create_emitter(transport_config, namespace)
        return LineageResource(emitter=emitter)
    except Exception:
        logging.getLogger(__name__).warning(
            "lineage_resource_load_failed", exc_info=True,
        )
        return NoOpLineageResource()


def _get_lineage_resource() -> Any:
    """Return the cached lineage resource, creating it on first call."""
    global _LINEAGE_RESOURCE
    if _LINEAGE_RESOURCE is None:
        _LINEAGE_RESOURCE = _load_lineage_resource()
    return _LINEAGE_RESOURCE



ARTIFACTS_PATH = PROJECT_DIR / "compiled_artifacts.json"
DUCKDB_PATH = "/tmp/financial_risk.duckdb"


_SAFE_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")


def _is_safe_identifier(name: str) -> bool:
    """Validate a SQL identifier against a safe pattern."""
    return bool(_SAFE_IDENTIFIER_RE.match(name))


def _load_iceberg_resources() -> dict[str, Any]:
    """Load Iceberg resources from compiled_artifacts.json."""
    if not ARTIFACTS_PATH.exists():
        return {}
    artifacts = CompiledArtifacts.model_validate_json(ARTIFACTS_PATH.read_text())
    return try_create_iceberg_resources(
        artifacts.plugins, governance=artifacts.governance,
    )


def _export_dbt_to_iceberg(context: Any) -> None:
    """Export dbt model outputs from DuckDB to Iceberg tables."""
    import duckdb
    from pyiceberg.exceptions import NoSuchTableError

    if not Path(DUCKDB_PATH).exists():
        context.log.warning(
            "DuckDB file not found at %s — skipping Iceberg export", DUCKDB_PATH,
        )
        return

    if not ARTIFACTS_PATH.exists():
        context.log.warning("compiled_artifacts.json not found — skipping Iceberg export")
        return

    artifacts = CompiledArtifacts.model_validate_json(ARTIFACTS_PATH.read_text())
    if artifacts.plugins is None or artifacts.plugins.catalog is None:
        context.log.info("No catalog plugin configured — skipping Iceberg export")
        return

    catalog_config = artifacts.plugins.catalog.config or {}
    storage_config = artifacts.plugins.storage.config or {} if artifacts.plugins.storage else {}

    registry = get_registry()
    catalog_type = artifacts.plugins.catalog.type
    catalog_plugin = registry.get(PluginType.CATALOG, catalog_type)
    validated_config = registry.configure(PluginType.CATALOG, catalog_type, catalog_config)
    if validated_config is None:
        context.log.warning(
            "Catalog plugin config for %s could not be validated — skipping Iceberg export",
            catalog_type,
        )
        return
    catalog_plugin = type(catalog_plugin)(config=validated_config)
    s3_config = {f"s3.{k}": v for k, v in storage_config.items()}
    catalog = catalog_plugin.connect(config=s3_config)

    product_namespace = "financial_risk"

    try:
        catalog.create_namespace(product_namespace)
        context.log.info("Created Iceberg namespace: %s", product_namespace)
    except Exception as exc:
        context.log.debug(
            "Namespace %s exists or creation failed: %s",
            product_namespace, type(exc).__name__,
        )

    conn = duckdb.connect(DUCKDB_PATH, read_only=True)
    try:
        tables_df = conn.execute(
            "SELECT table_schema, table_name FROM information_schema.tables "
            "WHERE table_schema NOT IN ('information_schema', 'pg_catalog')"
        ).fetchall()

        for schema_name, table_name in tables_df:
            if not _is_safe_identifier(schema_name) or not _is_safe_identifier(table_name):
                context.log.warning(
                    "Skipping unsafe identifier: %s.%s", schema_name, table_name,
                )
                continue
            if schema_name != 'main':
                qualified = f'"{schema_name}"."{table_name}"'
            else:
                qualified = f'"{table_name}"'
            query = f'SELECT * FROM {qualified}'  # nosec B608
            arrow_table = conn.execute(query).fetch_arrow_table()
            if arrow_table.num_rows == 0:
                continue

            iceberg_id = f"{product_namespace}.{table_name}"
            try:
                iceberg_table = catalog.load_table(iceberg_id)
                iceberg_table.overwrite(arrow_table)
            except NoSuchTableError:
                iceberg_table = catalog.create_table(
                    iceberg_id, schema=arrow_table.schema,
                )
                iceberg_table.append(arrow_table)
            context.log.info(
                "Exported %s to Iceberg (%d rows)", table_name, arrow_table.num_rows,
            )
    finally:
        conn.close()



@dbt_assets(
    manifest=MANIFEST_PATH,
    project=DbtProject(project_dir=DBT_PROJECT_DIR, profiles_dir=DBT_PROJECT_DIR),
    name="financial_risk_dbt_assets",
)
def financial_risk_dbt_assets(context, dbt: DbtCliResource):
    """Execute financial-risk dbt models as Dagster assets.

    This function is auto-generated by floe compile and uses dagster-dbt
    to execute all dbt models in this project as Dagster software-defined assets.
    """
    yield from dbt.cli(["build"], context=context).stream()

    lineage = _get_lineage_resource()  # noqa: F841

    # Post-build: export dbt output to Iceberg tables
    _export_dbt_to_iceberg(context)


# Create Definitions object for Dagster to discover
defs = Definitions(
    assets=[financial_risk_dbt_assets],
    resources={
        "dbt": DbtCliResource(
            project_dir=DBT_PROJECT_DIR,
            profiles_dir=DBT_PROJECT_DIR,
        ),
        **_load_iceberg_resources(),
    },
)
